spring.application.name=local_store

# If a ".env" exists, it loads it as properties
spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# Hibernate
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SHOW_FORMAT_SQL}

logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.security.web.*=debug

# Set max file size to 50MB and max request size to 50MB
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

# JWT
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}

storage.root=${STORAGE_ROOT}